name: Celery Task Runner

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute (minimum allowed by GitHub)
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  run-celery-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Celery Worker
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TMP_OUTPUT_PATH: ${{ secrets.TMP_OUTPUT_PATH }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          ENV: production
        run: |
          cd image_processor
          celery -A image_processor worker --loglevel=info --concurrency=1
