name: Celery Task Scheduler

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 15 minutes (adjust timing as needed)
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  run-celery-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Celery Worker
        env:
            REDIS_URL: ${{ secrets.REDIS_URL }}
            TMP_OUTPUT_PATH: ${{ secrets.TMP_OUTPUT_PATH }}
        run: |
          cd image_processor
          celery -A image_processor worker --loglevel=info --concurrency=1
